image: 
  - golang:latest
  - postgres:12.2-alpine

variables:
  REPO_NAME: gitlab.cs.ui.ac.id/ppl-fasilkom-ui/2022/Kelas-B/OOP/majapahit-service
  POSTGRES_DB:  ${DB_NAME:-majapahitdb}
  POSTGRES_USER: ${DB_PASSWORD:-root}
  POSTGRES_PASSWORD: ${DB_USERNAME:-postgres}
  POSTGRES_HOST_AUTH_METHOD: trust

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - test
  - build
  - deploy

Test:
  stage: test
  script:
    - go test -v $(go list ./... | grep -v ./main.go) 
    - go test $(go list ./... | grep -v ./main.go) -coverprofile coverage.cov && go tool cover -func coverage.cov
